#!/usr/bin/env python3
"""Learn and offline-fold one Qwen3.5 residual-stream rotation.

The learned matrix is global (one 5120 x 5120 R1).  Training uses the exact
HipFire activation oracles and an exact MQ4V2 fake-quant grid; export changes
only the BF16 Hugging Face checkpoint.  HipFire's format and runtime FWHT stay
unchanged.
"""
from __future__ import annotations

import argparse
import contextlib
import hashlib
import json
import math
import os
from pathlib import Path
import shutil
import sys
import time
from dataclasses import dataclass
from typing import Any

import numpy as np
import torch
from torch import nn
from safetensors import safe_open
from safetensors.torch import save_file

from capture import (
    ProducerSampler,
    RawTensor,
    SafeTensorSource,
    instantiate_layer,
    layer_forward,
    load_config,
    rotary_and_masks,
)
from quant_oracle import FUSED4, a4_forward, a4_ste, a8_forward, a8_ste, fwht256

SOURCE_DEFAULT = Path("/home/kaden/qcal/parents/qwen3.8-27b")
CAPTURE_DEFAULT = Path("/home/kaden/qcal/qat/l3")
OUT_DEFAULT = Path("/home/kaden/qcal/qat/l25")
CARD_UUIDS = {"GPU-9eb7aeda51c88ffd", "GPU-05f92432f2312a0e"}
HIDDEN = 5120
ALPHA = 0.35
SCHEMA = "hipfire.qat.spin_rotation.v1"


def atomic_json(path: Path, value: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temp = path.with_suffix(path.suffix + ".tmp")
    temp.write_text(json.dumps(value, indent=2, sort_keys=True) + "\n")
    os.replace(temp, path)


def sha256_file(path: Path, chunk_bytes: int = 32 << 20) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        while chunk := handle.read(chunk_bytes):
            digest.update(chunk)
    return digest.hexdigest()


def require_gpu() -> torch.device:
    visible = os.environ.get("ROCR_VISIBLE_DEVICES")
    if visible not in CARD_UUIDS:
        raise RuntimeError(
            "set ROCR_VISIBLE_DEVICES to card-A or card-E UUID; "
            f"got {visible!r}"
        )
    if not torch.cuda.is_available():
        raise RuntimeError("ROCm torch cannot see the selected GPU")
    return torch.device("cuda")


def bf16_gain(stored: torch.Tensor) -> torch.Tensor:
    """Qwen3.5 RMSNorm stores a delta; the real gain is 1 + weight."""
    return 1.0 + stored.float()


def compute_awq_scales(in_sum2: torch.Tensor, alpha: float = ALPHA) -> torch.Tensor:
    values = in_sum2.double().clamp(1e-12, 1e30)
    logs = values.log() * (0.5 * alpha)
    result = (logs - logs.mean()).exp().float().clamp(1e-2, 1e2)
    # Quantizer serializes the runtime sidecar as F16.  Search uses that grid.
    return result.half().float()


def cayley(a: torch.Tensor) -> torch.Tensor:
    """R=(I-A)(I+A)^-1 for skew A (polynomials commute)."""
    skew = 0.5 * (a - a.T)
    identity = torch.eye(skew.shape[0], dtype=skew.dtype, device=skew.device)
    return torch.linalg.solve(identity + skew, identity - skew)


def identity_rotation(device: torch.device) -> torch.Tensor:
    a = torch.zeros((HIDDEN, HIDDEN), dtype=torch.float32, device=device)
    rotation = cayley(a)
    identity = torch.eye(HIDDEN, dtype=torch.float32, device=device)
    if not torch.equal(rotation, identity):
        raise AssertionError("A=0 Cayley map did not reproduce R=I bitwise")
    return rotation


def orthogonality_error(rotation: torch.Tensor) -> tuple[float, float]:
    identity = torch.eye(rotation.shape[0], dtype=torch.float32, device=rotation.device)
    error = rotation.T @ rotation - identity
    return float(error.abs().max().item()), float(error.square().mean().sqrt().item())


def cayley_sgd_step(rotation: torch.Tensor, gradient: torch.Tensor, lr: float) -> tuple[torch.Tensor, float]:
    """Exact Cayley retraction for SpinQuant's square-matrix SGDG update."""
    # For square orthogonal R, the Riemannian gradient is generated by the
    # skew matrix G R^T - R G^T.  The norm-one cap is SpinQuant's SGDG guard.
    generator = gradient @ rotation.T - rotation @ gradient.T
    norm_one = generator.abs().sum(dim=0).max()
    step = min(float(lr), float((1.0 / (norm_one + 1e-8)).item()))
    identity = torch.eye(rotation.shape[0], dtype=torch.float32, device=rotation.device)
    lhs = identity + (0.5 * step) * generator
    rhs = (identity - (0.5 * step) * generator) @ rotation
    updated = torch.linalg.solve(lhs, rhs)
    return updated, step


def mq4v2_fake(weight: torch.Tensor) -> torch.Tensor:
    """Exact MQ4V2 F16-header/asymmetric-RTN forward with STE backward."""
    if weight.ndim != 2 or weight.shape[1] % 256:
        raise ValueError(f"MQ4V2 expects [M,K], K%256=0, got {tuple(weight.shape)}")
    shaped = weight.reshape(weight.shape[0], weight.shape[1] // 256, 2, 128)
    lo = shaped.amin(dim=-1, keepdim=True)
    hi = shaped.amax(dim=-1, keepdim=True)
    raw_step = (hi - lo) / 15.0
    step = raw_step.half().float()
    zero = lo.half().float()
    valid = (hi > lo) & (raw_step != 0.0) & (step != 0.0)
    safe_step = torch.where(valid, step, torch.ones_like(step))
    codes = torch.floor((shaped - zero) / safe_step + 0.5).clamp_(0.0, 15.0)
    decoded = torch.where(valid, codes * step + zero, zero).reshape_as(weight)
    return weight + (decoded - weight).detach()


def runtime_basis_rows(values: torch.Tensor) -> torch.Tensor:
    """Apply row-side F^T by transposing through the oracle's column F."""
    return fwht256(values.T.contiguous()).T.contiguous()


def relative_mse(value: torch.Tensor, reference: torch.Tensor) -> torch.Tensor:
    numerator = (value - reference).float().square().sum()
    denominator = reference.float().square().sum().clamp_min(1e-30)
    return numerator / denominator


def _reader_names(block: int) -> list[str]:
    prefix = f"model.language_model.layers.{block}."
    if block % 4 == 3:
        return [
            prefix + "self_attn.q_proj.weight",
            prefix + "self_attn.k_proj.weight",
            prefix + "self_attn.v_proj.weight",
        ]
    return [
        prefix + "linear_attn.in_proj_qkv.weight",
        prefix + "linear_attn.in_proj_z.weight",
        prefix + "linear_attn.in_proj_a.weight",
        prefix + "linear_attn.in_proj_b.weight",
    ]


def _site_names(block: int) -> tuple[str, str]:
    return (
        "input_norm_qkv" if block % 4 == 3 else "input_norm_qkvza",
        "post_attention_norm_gate_up",
    )


def _norm_name(block: int, site: str) -> str:
    which = "input_layernorm" if site.startswith("input_norm") else "post_attention_layernorm"
    return f"model.language_model.layers.{block}.{which}.weight"


def _site_weight_names(block: int, site: str) -> list[str]:
    if site.startswith("input_norm"):
        return _reader_names(block)
    prefix = f"model.language_model.layers.{block}.mlp."
    return [prefix + "gate_proj.weight", prefix + "up_proj.weight"]


@dataclass
class ProjectionSite:
    block: int
    name: str
    x_base_train: torch.Tensor
    x_base_heldout: torch.Tensor
    x_original_train: torch.Tensor
    x_original_heldout: torch.Tensor
    weight: torch.Tensor
    folded_weight: torch.Tensor
    scale: torch.Tensor
    train_order: torch.Tensor
    heldout_order: torch.Tensor

    def loss(
        self,
        rotation: torch.Tensor,
        batch: int,
        step: int,
        activation_weight: float,
    ) -> dict[str, torch.Tensor]:
        count = self.x_base_train.shape[0]
        offset = (step * batch) % count
        if offset + batch <= count:
            indices = self.train_order[offset : offset + batch]
        else:
            indices = torch.cat((self.train_order[offset:], self.train_order[: batch - (count - offset)]))
        xb = self.x_base_train.index_select(0, indices)
        xo = self.x_original_train.index_select(0, indices)
        metrics = self._metrics(rotation, xb, xo, ste=True)
        metrics["loss"] = (
            activation_weight * metrics["activation4"]
            + metrics["weight4"]
            + metrics["output4"]
            + 0.25 * metrics["output8"]
        )
        return metrics

    def heldout(self, rotation: torch.Tensor, limit: int) -> dict[str, torch.Tensor]:
        indices = self.heldout_order[: min(limit, self.heldout_order.numel())]
        xb = self.x_base_heldout.index_select(0, indices)
        xo = self.x_original_heldout.index_select(0, indices)
        return self._metrics(rotation, xb, xo, ste=False)

    def _metrics(
        self, rotation: torch.Tensor, xb: torch.Tensor, xo: torch.Tensor, ste: bool
    ) -> dict[str, torch.Tensor]:
        x_rotated = xb @ rotation
        w_rotated = self.folded_weight @ rotation
        z = runtime_basis_rows(x_rotated / self.scale)
        u = runtime_basis_rows(w_rotated * self.scale)
        qw = mq4v2_fake(u)
        if ste:
            qa4 = a4_ste(z.T.contiguous(), FUSED4).T
            qa8 = a8_ste(z.T.contiguous(), "f32").T
        else:
            qa4 = a4_forward(z.T.contiguous(), FUSED4)[0].T
            qa8 = a8_forward(z.T.contiguous(), "f32")[0].T
        reference = xo @ self.weight.T
        y4 = qa4 @ qw.T
        y8 = qa8 @ qw.T
        activation4 = relative_mse(qa4, z)
        weight4 = relative_mse(qw, u)
        output4 = relative_mse(y4, reference)
        output8 = relative_mse(y8, reference)
        total = activation4 + weight4 + output4 + 0.25 * output8
        return {
            "loss": total,
            "activation4": activation4,
            "weight4": weight4,
            "output4": output4,
            "output8": output8,
        }


def _sample_weight_rows(
    source: SafeTensorSource, names: list[str], rows: int, seed: int
) -> torch.Tensor:
    rng = np.random.Generator(np.random.PCG64(seed))
    shapes = [(name, int(source.get(name).shape[0])) for name in names]
    total = sum(size for _, size in shapes)
    chosen = np.sort(rng.choice(total, size=min(rows, total), replace=False))
    pieces: list[torch.Tensor] = []
    base = 0
    for name, size in shapes:
        local = chosen[(chosen >= base) & (chosen < base + size)] - base
        if local.size:
            full = source.get(name)
            pieces.append(full.index_select(0, torch.from_numpy(local.astype(np.int64))).float())
        base += size
    return torch.cat(pieces, dim=0)


def load_projection_sites(
    source_path: Path,
    capture_path: Path,
    blocks: list[int],
    weight_rows: int,
    device: torch.device,
    seed: int,
) -> tuple[list[ProjectionSite], dict[str, Any]]:
    manifest = json.loads((capture_path / "manifest.json").read_text())
    source = SafeTensorSource(source_path)
    sites: list[ProjectionSite] = []
    split_sequence = int(manifest["corpus"]["train_sequences"])
    seq_len = int(manifest["corpus"]["sequence_length"])
    for block in blocks:
        block_meta = manifest.get("capture", {}).get("blocks", {}).get(str(block))
        if not block_meta or block_meta.get("status") != "complete":
            raise RuntimeError(f"capture block {block} is not complete")
        for site_index, site_name in enumerate(_site_names(block)):
            meta = block_meta["producer_sites"][site_name]
            shape = tuple(int(v) for v in meta["shape"])
            array = np.memmap(capture_path / meta["file"], dtype="<f4", mode="r", shape=shape)
            global_indices = np.asarray(meta["global_sample_indices"], dtype=np.int64)
            is_train = global_indices < split_sequence * seq_len
            train = torch.from_numpy(np.asarray(array[is_train]).copy()).to(device)
            heldout = torch.from_numpy(np.asarray(array[~is_train]).copy()).to(device)
            gain = bf16_gain(source.get(_norm_name(block, site_name))).to(device)
            x_base_train = train / gain
            x_base_heldout = heldout / gain
            names = _site_weight_names(block, site_name)
            weight = _sample_weight_rows(
                source, names, weight_rows, seed + block * 101 + site_index
            ).to(device)
            folded_weight = weight * gain
            scale = compute_awq_scales(train.square().sum(dim=0), ALPHA)
            generator = torch.Generator(device=device).manual_seed(seed + block * 1009 + site_index)
            train_order = torch.randperm(train.shape[0], generator=generator, device=device)
            heldout_order = torch.randperm(heldout.shape[0], generator=generator, device=device)
            sites.append(
                ProjectionSite(
                    block,
                    site_name,
                    x_base_train,
                    x_base_heldout,
                    train,
                    heldout,
                    weight,
                    folded_weight,
                    scale,
                    train_order,
                    heldout_order,
                )
            )
    provenance = {
        "capture_manifest": str((capture_path / "manifest.json").resolve()),
        "capture_source_sha256": manifest["source"]["sha256"],
        "corpus_token_sha256": manifest["corpus"]["token_stream"]["sha256"],
        "blocks": blocks,
        "sites": [f"{site.block}:{site.name}" for site in sites],
    }
    return sites, provenance


def aggregate_metrics(
    sites: list[ProjectionSite], rotation: torch.Tensor, heldout_limit: int
) -> dict[str, float]:
    totals: dict[str, float] = {}
    with torch.no_grad():
        for site in sites:
            metrics = site.heldout(rotation, heldout_limit)
            for key, value in metrics.items():
                totals[key] = totals.get(key, 0.0) + float(value.item())
    count = float(len(sites))
    return {key: value / count for key, value in totals.items()}


class RuntimeQuantLinear(nn.Module):
    """Linear executed in HipFire's fixed AWQ/FWHT activation basis."""

    def __init__(self, qweight: torch.Tensor, scale: torch.Tensor, route: str):
        super().__init__()
        self.register_buffer("qweight", qweight.float())
        self.register_buffer("scale", scale.float())
        self.route = route
        self.in_features = int(qweight.shape[1])
        self.out_features = int(qweight.shape[0])

    def forward(self, value: torch.Tensor) -> torch.Tensor:
        dtype = value.dtype
        shape = value.shape[:-1]
        flat = value.reshape(-1, self.in_features).float()
        rotated = runtime_basis_rows(flat / self.scale)
        column = rotated.T.contiguous()
        if self.route == "a4":
            quantized = a4_forward(column, FUSED4)[0].T
        elif self.route == "a8":
            quantized = a8_forward(column, "f32")[0].T
        else:
            raise ValueError(self.route)
        output = quantized @ self.qweight.T
        return output.reshape(*shape, self.out_features).to(dtype)


def _replace_module(root: nn.Module, dotted: str, replacement: nn.Module) -> None:
    parent = root
    pieces = dotted.split(".")
    for piece in pieces[:-1]:
        parent = getattr(parent, piece)
    setattr(parent, pieces[-1], replacement)


def _block_scales(
    capture_path: Path, manifest: dict[str, Any], block: int, device: torch.device
) -> dict[str, torch.Tensor]:
    block_meta = manifest["capture"]["blocks"][str(block)]
    result: dict[str, torch.Tensor] = {}
    split_sequence = int(manifest["corpus"]["train_sequences"])
    seq_len = int(manifest["corpus"]["sequence_length"])
    for site, meta in block_meta["producer_sites"].items():
        shape = tuple(int(value) for value in meta["shape"])
        array = np.memmap(capture_path / meta["file"], dtype="<f4", mode="r", shape=shape)
        indices = np.asarray(meta["global_sample_indices"], dtype=np.int64)
        train = torch.from_numpy(
            np.asarray(array[indices < split_sequence * seq_len]).copy()
        ).to(device)
        result[site] = compute_awq_scales(train.square().sum(dim=0), ALPHA)
    return result


def _quantized_folded_layer(
    source: SafeTensorSource,
    config: Any,
    block: int,
    rotation: torch.Tensor,
    scales: dict[str, torch.Tensor],
    route: str,
    device: torch.device,
) -> nn.Module:
    layer = instantiate_layer(source, config, block, device)
    input_site, post_site = _site_names(block)
    specs: list[tuple[str, str, str]] = []
    if block % 4 == 3:
        specs.extend(
            (name, "reader", input_site)
            for name in ("self_attn.q_proj", "self_attn.k_proj", "self_attn.v_proj")
        )
        specs.append(("self_attn.o_proj", "writer", "mixer_out"))
    else:
        specs.extend(
            (name, "reader", input_site)
            for name in (
                "linear_attn.in_proj_qkv",
                "linear_attn.in_proj_z",
                "linear_attn.in_proj_a",
                "linear_attn.in_proj_b",
            )
        )
        specs.append(("linear_attn.out_proj", "writer", "mixer_out"))
    specs.extend(
        (
            ("mlp.gate_proj", "reader", post_site),
            ("mlp.up_proj", "reader", post_site),
            ("mlp.down_proj", "writer", "silu_mul_down"),
        )
    )
    input_gain = bf16_gain(layer.input_layernorm.weight).to(device)
    post_gain = bf16_gain(layer.post_attention_layernorm.weight).to(device)
    with torch.no_grad():
        for dotted, role, site in specs:
            module = layer
            for piece in dotted.split("."):
                module = getattr(module, piece)
            weight = module.weight.float()
            if role == "reader":
                gain = post_gain if dotted.startswith("mlp.") else input_gain
                natural = (weight * gain) @ rotation
            else:
                natural = rotation.T @ weight
            scale = scales[site]
            encoded = runtime_basis_rows(natural * scale)
            qweight = mq4v2_fake(encoded).detach()
            _replace_module(layer, dotted, RuntimeQuantLinear(qweight, scale, route))
        layer.input_layernorm.weight.zero_()
        layer.post_attention_layernorm.weight.zero_()
    layer.eval()
    return layer


def block_reconstruction_metrics(
    source_path: Path,
    capture_path: Path,
    blocks: list[int],
    rotation: torch.Tensor,
    sequences: int,
    tokens: int,
    device: torch.device,
) -> dict[str, Any]:
    """Measure held-out whole-block BF16 reconstruction on both runtime routes."""
    manifest = json.loads((capture_path / "manifest.json").read_text())
    config = load_config(source_path)
    source = SafeTensorSource(source_path)
    train_sequences = int(manifest["corpus"]["train_sequences"])
    selected = slice(train_sequences, train_sequences + sequences)
    route_rows: dict[str, list[dict[str, float]]] = {"a4": [], "a8": []}
    for block in blocks:
        input_meta = manifest["capture"]["boundaries"][str(block)]
        output_meta = manifest["capture"]["boundaries"][str(block + 1)]
        input_shape = tuple(int(value) for value in input_meta["shape"])
        output_shape = tuple(int(value) for value in output_meta["shape"])
        original_input = _read_bf16_memmap(
            capture_path / input_meta["file"], input_shape, selected
        )[:, :tokens].to(device)
        teacher = _read_bf16_memmap(
            capture_path / output_meta["file"], output_shape, selected
        )[:, :tokens].to(device)
        rotated_input = (original_input.float() @ rotation).to(torch.bfloat16)
        rotated_teacher = teacher.float() @ rotation
        position_embeddings, positions, causal = rotary_and_masks(
            config, tokens, device
        )
        scales = _block_scales(capture_path, manifest, block, device)
        for route in ("a4", "a8"):
            layer = _quantized_folded_layer(
                source, config, block, rotation, scales, route, device
            )
            with torch.inference_mode():
                output = layer_forward(
                    layer,
                    rotated_input,
                    position_embeddings,
                    positions,
                    causal,
                    str(config.layer_types[block]),
                ).float()
            error = output - rotated_teacher
            numerator = float(error.square().sum().item())
            denominator = float(rotated_teacher.square().sum().item())
            route_rows[route].append(
                {
                    "block": block,
                    "relative_mse": numerator / max(denominator, 1e-30),
                    "max_abs": float(error.abs().max().item()),
                    "rms": float(error.square().mean().sqrt().item()),
                    "reference_rms": float(
                        rotated_teacher.square().mean().sqrt().item()
                    ),
                }
            )
            del layer, output, error
            torch.cuda.empty_cache()
        del original_input, teacher, rotated_input, rotated_teacher
    return {
        route: {
            "mean_relative_mse": sum(row["relative_mse"] for row in rows)
            / len(rows),
            "blocks": rows,
        }
        for route, rows in route_rows.items()
    }


def fit(args: argparse.Namespace) -> dict[str, Any]:
    device = require_gpu()
    torch.manual_seed(args.seed)
    blocks = [int(value) for value in args.blocks.split(",")]
    sites, provenance = load_projection_sites(
        args.source, args.capture, blocks, args.weight_rows, device, args.seed
    )
    rotation = identity_rotation(device)
    initial_orth = orthogonality_error(rotation)
    initial = aggregate_metrics(sites, rotation, args.heldout_samples)
    initial_block = None
    if not args.skip_block_eval:
        initial_block = block_reconstruction_metrics(
            args.source,
            args.capture,
            blocks,
            rotation,
            args.block_eval_sequences,
            args.block_eval_tokens,
            device,
        )
        print(json.dumps({"step": 0, "block_reconstruction": initial_block}, sort_keys=True), flush=True)
    history: list[dict[str, Any]] = [{"step": 0, "heldout": initial}]
    started = time.monotonic()
    actual_steps: list[float] = []
    for step in range(args.steps):
        rotation = rotation.detach().requires_grad_(True)
        metrics_per_site = [
            site.loss(
                rotation,
                args.batch_samples,
                step,
                args.activation_weight,
            )
            for site in sites
        ]
        loss = torch.stack([metrics["loss"] for metrics in metrics_per_site]).mean()
        loss.backward()
        schedule = 0.5 * (1.0 + math.cos(math.pi * step / max(args.steps, 1)))
        requested_lr = args.lr * schedule
        with torch.no_grad():
            rotation, actual_lr = cayley_sgd_step(rotation, rotation.grad, requested_lr)
        actual_steps.append(actual_lr)
        number = step + 1
        if number % args.eval_every == 0 or number == args.steps:
            heldout = aggregate_metrics(sites, rotation, args.heldout_samples)
            row = {
                "step": number,
                "train_loss": float(loss.item()),
                "requested_lr": requested_lr,
                "actual_cayley_step": actual_lr,
                "heldout": heldout,
            }
            history.append(row)
            print(json.dumps(row, sort_keys=True), flush=True)
    final = history[-1]["heldout"]
    projection_a4_improvement = (initial["output4"] - final["output4"]) / max(
        initial["output4"], 1e-30
    )
    activation_improvement = (initial["activation4"] - final["activation4"]) / max(
        initial["activation4"], 1e-30
    )
    final_block = None
    if not args.skip_block_eval:
        final_block = block_reconstruction_metrics(
            args.source,
            args.capture,
            blocks,
            rotation,
            args.block_eval_sequences,
            args.block_eval_tokens,
            device,
        )
        print(
            json.dumps(
                {"step": args.steps, "block_reconstruction": final_block},
                sort_keys=True,
            ),
            flush=True,
        )
        initial_a4 = initial_block["a4"]["mean_relative_mse"]
        final_a4 = final_block["a4"]["mean_relative_mse"]
        a4_improvement = (initial_a4 - final_a4) / max(initial_a4, 1e-30)
        a8_feasible = (
            final_block["a8"]["mean_relative_mse"]
            <= 1.01 * initial_block["a8"]["mean_relative_mse"]
        )
    else:
        a4_improvement = projection_a4_improvement
        a8_feasible = final["output8"] <= 1.01 * initial["output8"]
    gate_passed = a4_improvement >= args.kill_threshold and a8_feasible
    orth = orthogonality_error(rotation)
    args.out.mkdir(parents=True, exist_ok=True)
    rotation_path = args.out / "R1.pt"
    torch.save(rotation.detach().cpu().to(torch.float32), rotation_path)
    receipt = {
        "schema_version": SCHEMA,
        "status": "kill_pass" if gate_passed else "killed_convergence",
        "method": "SpinQuant-style exact Cayley retraction; R initialized by A=0 in R=(I-A)(I+A)^-1",
        "source": str(args.source.resolve()),
        "source_index_sha256": sha256_file(args.source / "model.safetensors.index.json"),
        "provenance": provenance,
        "alpha": ALPHA,
        "steps": args.steps,
        "requested_lr": args.lr,
        "batch_samples_per_site": args.batch_samples,
        "weight_rows_per_site": args.weight_rows,
        "heldout_samples_per_site": args.heldout_samples,
        "activation_loss_weight": args.activation_weight,
        "initial_A_zero_identity_bitwise": True,
        "initial_orthogonality_max_rms": list(initial_orth),
        "final_orthogonality_max_rms": list(orth),
        "initial": initial,
        "final": final,
        "initial_block_reconstruction": initial_block,
        "final_block_reconstruction": final_block,
        "heldout_block_a4_improvement": a4_improvement,
        "heldout_projection_output4_improvement": projection_a4_improvement,
        "heldout_activation4_improvement": activation_improvement,
        "a8_feasible_within_one_percent": a8_feasible,
        "kill_threshold": args.kill_threshold,
        "wall_clock_seconds": time.monotonic() - started,
        "actual_cayley_step_min": min(actual_steps),
        "actual_cayley_step_max": max(actual_steps),
        "rotation_file": str(rotation_path.resolve()),
        "rotation_sha256": sha256_file(rotation_path),
        "history": history,
        "environment": {
            "python": sys.executable,
            "torch": torch.__version__,
            "torch_hip": torch.version.hip,
            "device": torch.cuda.get_device_name(),
            "rocr_visible_devices": os.environ.get("ROCR_VISIBLE_DEVICES"),
        },
    }
    atomic_json(args.out / "fit-receipt.json", receipt)
    print(json.dumps(receipt, indent=2, sort_keys=True))
    return receipt


def fold_audit(source_path: Path) -> dict[str, Any]:
    index = json.loads((source_path / "model.safetensors.index.json").read_text())
    names = set(index["weight_map"])
    expected: set[str] = {
        "model.language_model.embed_tokens.weight",
        "model.language_model.norm.weight",
        "lm_head.weight",
    }
    readers: list[str] = []
    writers: list[str] = []
    norms: list[str] = []
    for block in range(64):
        prefix = f"model.language_model.layers.{block}."
        layer_readers = _reader_names(block) + [
            prefix + "mlp.gate_proj.weight",
            prefix + "mlp.up_proj.weight",
        ]
        layer_writers = [
            prefix + ("self_attn.o_proj.weight" if block % 4 == 3 else "linear_attn.out_proj.weight"),
            prefix + "mlp.down_proj.weight",
        ]
        layer_norms = [
            prefix + "input_layernorm.weight",
            prefix + "post_attention_layernorm.weight",
        ]
        readers.extend(layer_readers)
        writers.extend(layer_writers)
        norms.extend(layer_norms)
        expected.update(layer_readers + layer_writers + layer_norms)
    missing = sorted(expected - names)
    text_names = sorted(name for name in names if name.startswith("model.language_model.") or name == "lm_head.weight")
    allowed_untouched_suffixes = (
        ".A_log",
        ".dt_bias",
        ".conv1d.weight",
        ".linear_attn.norm.weight",
        ".self_attn.q_norm.weight",
        ".self_attn.k_norm.weight",
    )
    known = expected | {name for name in text_names if name.endswith(allowed_untouched_suffixes)}
    unknown = sorted(set(text_names) - known)
    if missing or unknown:
        raise RuntimeError(f"fold tensor audit failed: missing={missing}, unknown={unknown}")
    return {
        "readers": readers,
        "writers": writers,
        "norms": norms,
        "reader_count": len(readers),
        "writer_count": len(writers),
        "norm_count": len(norms),
        "bias_tensors": [name for name in text_names if name.endswith(".bias")],
        "unknown_residual_side_tensors": unknown,
        "untouched_text_tensors": sorted(set(text_names) - expected),
    }


def synthetic_fold_identity(source_path: Path, rotation: torch.Tensor, device: torch.device) -> dict[str, float]:
    source = SafeTensorSource(source_path)
    generator = torch.Generator(device=device).manual_seed(20260920)
    x = torch.randn((32, HIDDEN), generator=generator, device=device)
    x = x / x.square().mean(dim=-1, keepdim=True).sqrt()
    block = 0
    norm_name = f"model.language_model.layers.{block}.input_layernorm.weight"
    weight_name = f"model.language_model.layers.{block}.linear_attn.in_proj_b.weight"
    gain = bf16_gain(source.get(norm_name)).to(device)
    weight = source.get(weight_name).float().to(device)
    original = (x * gain) @ weight.T
    rotated_x = x @ rotation
    folded_w = (weight * gain) @ rotation
    folded = rotated_x @ folded_w.T
    error = folded - original
    return {
        "max_abs": float(error.abs().max().item()),
        "rms": float(error.square().mean().sqrt().item()),
        "reference_rms": float(original.square().mean().sqrt().item()),
        "relative_rms": float(error.square().sum().sqrt().div(original.square().sum().sqrt()).item()),
    }


def _load_rotation(path: Path, device: torch.device) -> torch.Tensor:
    value = torch.load(path, map_location="cpu", weights_only=True)
    if isinstance(value, dict):
        value = value.get("R1", value.get("rotation"))
    if not isinstance(value, torch.Tensor) or tuple(value.shape) != (HIDDEN, HIDDEN):
        raise ValueError(f"rotation must be F32[{HIDDEN},{HIDDEN}]")
    rotation = value.float().to(device)
    maximum, _ = orthogonality_error(rotation)
    if maximum > 5e-4:
        raise ValueError(f"rotation is not orthogonal: max |R^T R-I|={maximum}")
    return rotation


def audit_command(args: argparse.Namespace) -> dict[str, Any]:
    device = require_gpu()
    rotation = identity_rotation(device) if args.rotation is None else _load_rotation(args.rotation, device)
    audit = fold_audit(args.source)
    identity = synthetic_fold_identity(args.source, rotation, device)
    result = {
        "schema_version": SCHEMA,
        "audit": audit,
        "real_arithmetic_identity": identity,
        "orthogonality_max_rms": list(orthogonality_error(rotation)),
        "rotation": "identity" if args.rotation is None else str(args.rotation.resolve()),
    }
    if identity["relative_rms"] > 2e-5:
        raise RuntimeError(f"fold identity failed: {identity}")
    args.out.mkdir(parents=True, exist_ok=True)
    atomic_json(args.out / "fold-audit.json", result)
    print(json.dumps(result, indent=2, sort_keys=True))
    return result


def _fold_tensor(
    name: str,
    tensor: torch.Tensor,
    rotation: torch.Tensor,
    source: SafeTensorSource,
    readers: set[str],
    writers: set[str],
    norms: set[str],
) -> torch.Tensor:
    device = rotation.device
    if name == "model.language_model.embed_tokens.weight":
        return (tensor.float().to(device) @ rotation).to(torch.bfloat16).cpu()
    if name == "lm_head.weight":
        gain = bf16_gain(source.get("model.language_model.norm.weight")).to(device)
        return ((tensor.float().to(device) * gain) @ rotation).to(torch.bfloat16).cpu()
    if name == "model.language_model.norm.weight" or name in norms:
        return torch.zeros_like(tensor, dtype=torch.bfloat16)
    if name in readers:
        block_prefix = name.rsplit(".", 3)[0]
        if ".mlp." in name:
            norm_name = block_prefix.rsplit(".mlp", 1)[0] + ".post_attention_layernorm.weight"
        else:
            layer_prefix = name.split(".linear_attn.", 1)[0].split(".self_attn.", 1)[0]
            norm_name = layer_prefix + ".input_layernorm.weight"
        gain = bf16_gain(source.get(norm_name)).to(device)
        return ((tensor.float().to(device) * gain) @ rotation).to(torch.bfloat16).cpu()
    if name in writers:
        return (rotation.T @ tensor.float().to(device)).to(torch.bfloat16).cpu()
    return tensor


def fold_checkpoint(args: argparse.Namespace) -> dict[str, Any]:
    device = require_gpu()
    rotation = _load_rotation(args.rotation, device)
    audit = fold_audit(args.source)
    readers, writers, norms = map(set, (audit["readers"], audit["writers"], audit["norms"]))
    source = SafeTensorSource(args.source)
    args.output.mkdir(parents=True, exist_ok=True)
    index = json.loads((args.source / "model.safetensors.index.json").read_text())
    shards = sorted(set(index["weight_map"].values()))
    shard_receipts: list[dict[str, Any]] = []
    started = time.monotonic()
    for shard_name in shards:
        input_path = args.source / shard_name
        output_path = args.output / shard_name
        with safe_open(input_path, framework="pt", device="cpu") as handle:
            metadata = handle.metadata()
            tensors: dict[str, torch.Tensor] = {}
            for name in handle.keys():
                tensors[name] = _fold_tensor(
                    name, handle.get_tensor(name), rotation, source, readers, writers, norms
                ).contiguous()
            save_file(tensors, output_path, metadata=metadata)
        shard_receipts.append(
            {"file": shard_name, "bytes": output_path.stat().st_size, "sha256": sha256_file(output_path)}
        )
        print(f"folded {shard_name}", flush=True)
    for path in args.source.iterdir():
        if path.name.startswith("model-") and path.suffix == ".safetensors":
            continue
        if path.name == "model.safetensors.index.json":
            continue
        destination = args.output / path.name
        if path.is_file():
            shutil.copy2(path, destination)
    shutil.copy2(args.source / "model.safetensors.index.json", args.output / "model.safetensors.index.json")
    receipt = {
        "schema_version": SCHEMA,
        "source": str(args.source.resolve()),
        "output": str(args.output.resolve()),
        "rotation": str(args.rotation.resolve()),
        "rotation_sha256": sha256_file(args.rotation),
        "fold_audit": audit,
        "shards": shard_receipts,
        "total_safetensor_bytes": sum(row["bytes"] for row in shard_receipts),
        "wall_clock_seconds": time.monotonic() - started,
    }
    atomic_json(args.output / "spin-fold-receipt.json", receipt)
    return receipt


def capture_small(args: argparse.Namespace) -> dict[str, Any]:
    """Stream 64 approved disjoint sequences and retain only three gate blocks."""
    device = require_gpu()
    if (args.out / "manifest.json").exists():
        raise FileExistsError(f"refusing to overwrite existing capture: {args.out}")
    blocks = sorted({int(value) for value in args.blocks.split(",")})
    if not blocks or blocks[0] < 0 or blocks[-1] >= 64:
        raise ValueError(f"invalid target blocks: {blocks}")
    base_manifest = json.loads((args.corpus / "manifest.json").read_text())
    base_sequences = base_manifest["corpus"]["sequences"]
    chosen: list[dict[str, Any]] = []
    for split, per_source in (("train", 24), ("heldout", 8)):
        for source_prefix in ("wikitext2-train", "c4-train"):
            rows = [
                row
                for row in base_sequences
                if row["split"] == split and row["source"].startswith(source_prefix)
            ]
            rows.sort(key=lambda row: row["token_sha256"])
            if len(rows) < per_source:
                raise RuntimeError(
                    f"corpus has only {len(rows)} {split} {source_prefix} sequences"
                )
            chosen.extend(rows[:per_source])
    chosen.sort(key=lambda row: (row["split"] != "train", row["source"], row["token_sha256"]))
    if len(chosen) != 64 or sum(row["split"] == "train" for row in chosen) != 48:
        raise AssertionError("small capture selection is not 48 train + 16 heldout")

    seq_len = int(base_manifest["corpus"]["sequence_length"])
    base_total = int(base_manifest["corpus"]["total_sequences"])
    token_meta = base_manifest["corpus"]["token_stream"]
    base_tokens = np.memmap(
        args.corpus / token_meta["file"],
        dtype="<u4",
        mode="r",
        shape=(base_total, seq_len),
    )
    args.out.mkdir(parents=True, exist_ok=False)
    corpus_dir = args.out / "corpus"
    corpus_dir.mkdir()
    tensors_dir = args.out / "tensors"
    (tensors_dir / "boundaries").mkdir(parents=True)
    selected_tokens = np.stack(
        [np.asarray(base_tokens[int(row["sequence_id"])]).copy() for row in chosen]
    ).astype("<u4", copy=False)
    token_path = corpus_dir / "tokens.u32"
    token_path.write_bytes(selected_tokens.tobytes(order="C"))
    sequences: list[dict[str, Any]] = []
    for sequence_id, row in enumerate(chosen):
        copied = dict(row)
        copied["source_sequence_id"] = int(row["sequence_id"])
        copied["sequence_id"] = sequence_id
        copied["token_file_offset_bytes"] = sequence_id * seq_len * 4
        sequences.append(copied)
    manifest: dict[str, Any] = {
        "schema_version": SCHEMA,
        "source": base_manifest["source"],
        "corpus": {
            "selection": "24 WT2-train + 24 C4-train; 8 heldout from each; reused only the C2 corpus tokenization/disjointness proof",
            "source_manifest": str((args.corpus / "manifest.json").resolve()),
            "source_manifest_sha256_at_selection": sha256_file(args.corpus / "manifest.json"),
            "sequence_length": seq_len,
            "total_sequences": 64,
            "train_sequences": 48,
            "heldout_sequences": 16,
            "sequences": sequences,
            "token_stream": {
                "file": "corpus/tokens.u32",
                "shape": [64, seq_len],
                "dtype": "uint32-le",
                "sha256": sha256_file(token_path),
            },
            "disjointness": base_manifest["corpus"]["disjointness"],
        },
        "capture": {
            "status": "capturing",
            "target_blocks": blocks,
            "producer_sample_count_per_block": args.producer_samples,
            "boundaries": {},
            "blocks": {},
            "device_uuid": os.environ.get("ROCR_VISIBLE_DEVICES"),
        },
    }
    atomic_json(args.out / "manifest.json", manifest)
    config = load_config(args.source)
    source = SafeTensorSource(args.source)
    shape = (64, seq_len, HIDDEN)
    scratch_a = args.out / ".stream-a.bf16"
    scratch_b = args.out / ".stream-b.bf16"
    current = RawTensor(scratch_a, shape, "bfloat16", "w+")
    embedding = source.get("model.language_model.embed_tokens.weight").to(
        device=device, dtype=torch.bfloat16
    )
    with torch.inference_mode():
        for sequence in range(64):
            ids = torch.from_numpy(
                selected_tokens[sequence].astype(np.int64, copy=True)
            ).to(device)
            hidden = torch.nn.functional.embedding(ids, embedding)
            current.write_torch(sequence, hidden)
    current.flush()
    del embedding, hidden, ids
    torch.cuda.empty_cache()
    position_embeddings, positions, causal = rotary_and_masks(config, seq_len, device)
    started = time.monotonic()
    current_path, next_path = scratch_a, scratch_b
    for block in range(blocks[-1] + 1):
        current = RawTensor(current_path, shape, "bfloat16", "r")
        following = RawTensor(next_path, shape, "bfloat16", "w+")
        target = block in blocks
        if target:
            boundary_path = tensors_dir / "boundaries" / f"boundary_{block:02d}.bf16"
            current.flush()
            shutil.copyfile(current_path, boundary_path)
            manifest["capture"]["boundaries"][str(block)] = {
                "file": str(boundary_path.relative_to(args.out)),
                "shape": list(shape),
                "axes": ["sequence", "token", "hidden"],
                "dtype": "bfloat16-le",
                "bytes": boundary_path.stat().st_size,
            }
        layer = instantiate_layer(source, config, block, device)
        block_type = str(config.layer_types[block])
        sampler = None
        if target:
            sampler = ProducerSampler(
                block,
                args.out,
                args.producer_samples,
                HIDDEN,
                64,
                seq_len,
                args.seed,
            )
            sampler.install(layer)
        with torch.inference_mode():
            for sequence in range(64):
                if sampler is not None:
                    sampler.current_sequence_start = sequence
                    sampler.current_sequence_count = 1
                hidden = current.read_torch(sequence, device).unsqueeze(0)
                output = layer_forward(
                    layer,
                    hidden,
                    position_embeddings,
                    positions,
                    causal,
                    block_type,
                )
                following.write_torch(sequence, output[0])
        following.flush()
        if target:
            output_boundary_path = (
                tensors_dir / "boundaries" / f"boundary_{block + 1:02d}.bf16"
            )
            shutil.copyfile(next_path, output_boundary_path)
            manifest["capture"]["boundaries"][str(block + 1)] = {
                "file": str(output_boundary_path.relative_to(args.out)),
                "shape": list(shape),
                "axes": ["sequence", "token", "hidden"],
                "dtype": "bfloat16-le",
                "bytes": output_boundary_path.stat().st_size,
            }
            producer_meta = sampler.close()
            for meta in producer_meta.values():
                meta["file"] = str(Path(meta["file"]).relative_to(args.out))
            manifest["capture"]["blocks"][str(block)] = {
                "status": "complete",
                "type": block_type,
                "input_boundary": str(block),
                "output_boundary": str(block + 1),
                "producer_sites": producer_meta,
            }
            atomic_json(args.out / "manifest.json", manifest)
        del layer, current, following, hidden, output, sampler
        torch.cuda.empty_cache()
        current_path, next_path = next_path, current_path
        print(f"streamed block {block:02d}/{blocks[-1]:02d}", flush=True)
    for scratch in (scratch_a, scratch_b):
        with contextlib.suppress(FileNotFoundError):
            scratch.unlink()
    manifest["capture"]["status"] = "complete"
    manifest["capture"]["wall_clock_seconds"] = time.monotonic() - started
    atomic_json(args.out / "manifest.json", manifest)
    result = {
        "manifest": str((args.out / "manifest.json").resolve()),
        "blocks": blocks,
        "train_sequences": 48,
        "heldout_sequences": 16,
        "token_sha256": manifest["corpus"]["token_stream"]["sha256"],
        "wall_clock_seconds": manifest["capture"]["wall_clock_seconds"],
    }
    print(json.dumps(result, indent=2, sort_keys=True))
    return result


def repair_small_producers(args: argparse.Namespace) -> dict[str, Any]:
    """Re-capture producer samples by explicitly exposing each producer."""
    device = require_gpu()
    manifest_path = args.capture / "manifest.json"
    manifest = json.loads(manifest_path.read_text())
    blocks = [int(value) for value in manifest["capture"]["target_blocks"]]
    config = load_config(args.source)
    source = SafeTensorSource(args.source)
    seq_count = int(manifest["corpus"]["total_sequences"])
    seq_len = int(manifest["corpus"]["sequence_length"])
    shape = (seq_count, seq_len, HIDDEN)
    position_embeddings, positions, causal = rotary_and_masks(config, seq_len, device)
    for block in blocks:
        boundary_meta = manifest["capture"]["boundaries"][str(block)]
        boundary = RawTensor(
            args.capture / boundary_meta["file"], shape, "bfloat16", "r"
        )
        layer = instantiate_layer(source, config, block, device)
        block_type = str(config.layer_types[block])
        sampler = ProducerSampler(
            block,
            args.capture,
            int(manifest["capture"]["producer_sample_count_per_block"]),
            HIDDEN,
            seq_count,
            seq_len,
            args.seed,
        )
        if block_type == "linear_attention":
            mixer = layer.linear_attn
            output_projection = mixer.out_proj
            mixer.out_proj = nn.Identity()
        else:
            mixer = layer.self_attn
            output_projection = mixer.o_proj
            mixer.o_proj = nn.Identity()
        input_site = next(site for site in sampler.specs if site.startswith("input_norm"))
        with torch.inference_mode():
            for sequence in range(seq_count):
                hidden = boundary.read_torch(sequence, device).unsqueeze(0)
                input_norm = layer.input_layernorm(hidden)
                if block_type == "linear_attention":
                    mixer_input = mixer(
                        hidden_states=input_norm,
                        cache_params=None,
                        attention_mask=None,
                    )
                else:
                    mixer_input, _ = mixer(
                        hidden_states=input_norm,
                        position_embeddings=position_embeddings,
                        attention_mask=causal,
                        past_key_values=None,
                        position_ids=positions,
                    )
                mixer_output = output_projection(mixer_input)
                after_mixer = hidden + mixer_output
                post_norm = layer.post_attention_layernorm(after_mixer)
                silu_mul = (
                    layer.mlp.act_fn(layer.mlp.gate_proj(post_norm))
                    * layer.mlp.up_proj(post_norm)
                )
                lo = sequence * seq_len
                hi = lo + seq_len
                begin = int(np.searchsorted(sampler.global_indices, lo, side="left"))
                end = int(np.searchsorted(sampler.global_indices, hi, side="left"))
                rows = np.arange(begin, end, dtype=np.int64)
                local_positions = sampler.global_indices[begin:end] - lo
                if rows.size:
                    index = torch.from_numpy(local_positions).to(device=device)
                    values = {
                        input_site: input_norm,
                        "mixer_out": mixer_input,
                        "post_attention_norm_gate_up": post_norm,
                        "silu_mul_down": silu_mul,
                    }
                    for site, value in values.items():
                        flat = value.reshape(-1, value.shape[-1])
                        selected = flat.index_select(0, index).float()
                        payload = sampler.tensors[site].write_torch(rows, selected)
                        sampler.hashers[site].update(payload)
        if block_type == "linear_attention":
            mixer.out_proj = output_projection
        else:
            mixer.o_proj = output_projection
        producer_meta = sampler.close()
        for meta in producer_meta.values():
            meta["file"] = str(Path(meta["file"]).relative_to(args.capture))
        manifest["capture"]["blocks"][str(block)]["producer_sites"] = producer_meta
        atomic_json(manifest_path, manifest)
        del layer, boundary, hidden, sampler
        torch.cuda.empty_cache()
        print(f"repaired producer block {block:02d}", flush=True)
    result = {
        "manifest": str(manifest_path.resolve()),
        "blocks": blocks,
        "producer_samples": manifest["capture"]["producer_sample_count_per_block"],
    }
    print(json.dumps(result, indent=2, sort_keys=True))
    return result


def _read_bf16_memmap(path: Path, shape: tuple[int, ...], index: Any) -> torch.Tensor:
    array = np.memmap(path, dtype=np.uint16, mode="r", shape=shape)
    return torch.from_numpy(np.asarray(array[index]).copy()).view(torch.bfloat16)


def parity(args: argparse.Namespace) -> dict[str, Any]:
    """Layer-streamed eight-sequence BF16 parity without loading two 27B models."""
    device = require_gpu()
    rotation = _load_rotation(args.rotation, device)
    manifest = json.loads((args.capture / "manifest.json").read_text())
    config = load_config(args.source)
    source = SafeTensorSource(args.source)
    tokens_meta = manifest["corpus"]["token_stream"]
    seq_count = len(manifest["corpus"]["sequences"])
    seq_len = int(manifest["corpus"]["sequence_length"])
    tokens = np.memmap(
        args.capture / tokens_meta["file"], dtype="<u4", mode="r", shape=(seq_count, seq_len)
    )
    ids = torch.from_numpy(np.asarray(tokens[:8, : args.tokens]).astype(np.int64, copy=True)).to(device)
    embedding = source.get("model.language_model.embed_tokens.weight").to(device=device, dtype=torch.bfloat16)
    original = torch.nn.functional.embedding(ids, embedding)
    rotated_embedding = (embedding.float() @ rotation).to(torch.bfloat16)
    folded = torch.nn.functional.embedding(ids, rotated_embedding)
    del embedding, rotated_embedding
    per_block: list[dict[str, float]] = []
    pos, positions, causal = rotary_and_masks(config, args.tokens, device)
    audit = fold_audit(args.source)
    readers, writers, norms = map(set, (audit["readers"], audit["writers"], audit["norms"]))
    with torch.inference_mode():
        for block in range(config.num_hidden_layers):
            layer = instantiate_layer(source, config, block, device)
            block_type = str(config.layer_types[block])
            original = layer_forward(layer, original, pos, positions, causal, block_type)
            prefix = f"model.language_model.layers.{block}."
            for local_name, parameter in list(layer.named_parameters()):
                full_name = prefix + local_name
                folded_value = _fold_tensor(
                    full_name,
                    parameter.detach().cpu(),
                    rotation,
                    source,
                    readers,
                    writers,
                    norms,
                ).to(device)
                parameter.data.copy_(folded_value)
            folded = layer_forward(layer, folded, pos, positions, causal, block_type)
            expected = (original.float() @ rotation).to(torch.bfloat16)
            error = folded.float() - expected.float()
            per_block.append(
                {
                    "block": block,
                    "max_abs": float(error.abs().max().item()),
                    "rms": float(error.square().mean().sqrt().item()),
                }
            )
            del layer, expected, error
            torch.cuda.empty_cache()
    final_gain = bf16_gain(source.get("model.language_model.norm.weight")).to(device)
    original_norm = original.float() * torch.rsqrt(original.float().square().mean(-1, keepdim=True) + config.rms_norm_eps)
    original_norm = (original_norm * final_gain).to(torch.bfloat16)
    folded_norm = folded.float() * torch.rsqrt(folded.float().square().mean(-1, keepdim=True) + config.rms_norm_eps)
    folded_norm = folded_norm.to(torch.bfloat16)
    head = source.get("lm_head.weight")
    max_abs = 0.0
    sum_square = 0.0
    count = 0
    with torch.inference_mode():
        for start in range(0, head.shape[0], args.head_rows):
            chunk = head[start : start + args.head_rows].to(device=device, dtype=torch.bfloat16)
            original_logits = original_norm @ chunk.T
            folded_head = ((chunk.float() * final_gain) @ rotation).to(torch.bfloat16)
            folded_logits = folded_norm @ folded_head.T
            error = folded_logits.float() - original_logits.float()
            max_abs = max(max_abs, float(error.abs().max().item()))
            sum_square += float(error.square().sum().item())
            count += error.numel()
    result = {
        "schema_version": SCHEMA,
        "sequences": 8,
        "tokens_per_sequence": args.tokens,
        "logits_max_abs": max_abs,
        "logits_rms": math.sqrt(sum_square / count),
        "block_max_abs": max(row["max_abs"] for row in per_block),
        "block_rms_max": max(row["rms"] for row in per_block),
        "per_block": per_block,
    }
    args.out.mkdir(parents=True, exist_ok=True)
    atomic_json(args.out / "fold-parity.json", result)
    print(json.dumps(result, indent=2, sort_keys=True))
    return result


def parser() -> argparse.ArgumentParser:
    root = argparse.ArgumentParser(description=__doc__)
    sub = root.add_subparsers(dest="command", required=True)

    audit = sub.add_parser("audit", help="audit residual-side tensors and prove fold identity")
    audit.add_argument("--source", type=Path, default=SOURCE_DEFAULT)
    audit.add_argument("--rotation", type=Path)
    audit.add_argument("--out", type=Path, default=OUT_DEFAULT)

    small = sub.add_parser(
        "capture-small",
        help="stream a 64-sequence disjoint corpus and retain only gate blocks",
    )
    small.add_argument("--source", type=Path, default=SOURCE_DEFAULT)
    small.add_argument("--corpus", type=Path, default=CAPTURE_DEFAULT)
    small.add_argument("--out", type=Path, required=True)
    small.add_argument("--blocks", default="0,31,60")
    small.add_argument("--producer-samples", type=int, default=4096)
    small.add_argument("--seed", type=int, default=20260920)

    repair = sub.add_parser(
        "repair-small-producers",
        help="re-capture producer samples for an existing small gate capture",
    )
    repair.add_argument("--source", type=Path, default=SOURCE_DEFAULT)
    repair.add_argument("--capture", type=Path, required=True)
    repair.add_argument("--seed", type=int, default=20260920)

    train = sub.add_parser("fit", help="fit R1 against captured projection sites")
    train.add_argument("--source", type=Path, default=SOURCE_DEFAULT)
    train.add_argument("--capture", type=Path, default=CAPTURE_DEFAULT)
    train.add_argument("--out", type=Path, default=OUT_DEFAULT)
    train.add_argument("--blocks", default="0,31,60")
    train.add_argument("--steps", type=int, default=50)
    train.add_argument("--lr", type=float, default=1.5)
    train.add_argument("--batch-samples", type=int, default=128)
    train.add_argument("--heldout-samples", type=int, default=512)
    train.add_argument("--weight-rows", type=int, default=128)
    train.add_argument("--eval-every", type=int, default=10)
    train.add_argument("--kill-threshold", type=float, default=0.10)
    train.add_argument("--seed", type=int, default=20260920)
    train.add_argument("--activation-weight", type=float, default=1.0)
    train.add_argument("--block-eval-sequences", type=int, default=2)
    train.add_argument("--block-eval-tokens", type=int, default=64)
    train.add_argument("--skip-block-eval", action="store_true")

    fold = sub.add_parser("fold", help="write a rotated BF16 Hugging Face checkpoint")
    fold.add_argument("--source", type=Path, default=SOURCE_DEFAULT)
    fold.add_argument("--rotation", type=Path, required=True)
    fold.add_argument("--output", type=Path, required=True)

    check = sub.add_parser("parity", help="stream 8 sequences through original and folded BF16 models")
    check.add_argument("--source", type=Path, default=SOURCE_DEFAULT)
    check.add_argument("--capture", type=Path, default=CAPTURE_DEFAULT)
    check.add_argument("--rotation", type=Path, required=True)
    check.add_argument("--out", type=Path, default=OUT_DEFAULT)
    check.add_argument("--tokens", type=int, default=32)
    check.add_argument("--head-rows", type=int, default=8192)
    return root


def main() -> None:
    args = parser().parse_args()
    if args.command == "audit":
        audit_command(args)
    elif args.command == "capture-small":
        capture_small(args)
    elif args.command == "repair-small-producers":
        repair_small_producers(args)
    elif args.command == "fit":
        receipt = fit(args)
        if receipt["status"] == "killed_convergence":
            raise SystemExit(3)
    elif args.command == "fold":
        print(json.dumps(fold_checkpoint(args), indent=2, sort_keys=True))
    elif args.command == "parity":
        parity(args)
    else:
        raise AssertionError(args.command)


if __name__ == "__main__":
    main()
