// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2026 Kaden Schutt
// hipfire — see LICENSE and NOTICE in the project root.
//! Deterministic weight-byte fixtures shared by this crate's tests.
//!
//! Deterministic rather than random on purpose: the payload must exercise both
//! nibbles of every packed byte, the high bits of the 3/6-bit cross-byte packs,
//! and negative Q8 codes, while the affine/scale header stays in a range that
//! keeps every decoded value finite — an `Inf`/`NaN` in a fixture makes the
//! result depend on the ISA's NaN payload (and `Inf * 0.0` in the dot product
//! would poison a whole row).
//!
//! The payload is `(i * 37 + 11) & 0xFF`, which is a bijection on the low byte,
//! so 128 bytes cover both nibble positions of every value. The expectation
//! tables in [`crate::quant`]'s tests were generated by running
//! `hipfire_runtime::weight_backend::dequantize_weight_to_f32` over
//! [`group_bytes(base, 0)`](group_bytes) at implementation time.

use crate::quant::CpuQuant;

/// Small values that are exact in f16, bf16 and f32: `0, 1, -1, 2, -2, 3, -3, 5`.
const SMALL_F16: [u16; 8] = [
    0x0000, 0x3c00, 0xbc00, 0x4000, 0xc000, 0x4200, 0xc200, 0x4500,
];
const SMALL_BF16: [u16; 8] = [
    0x0000, 0x3f80, 0xbf80, 0x4000, 0xc000, 0x4040, 0xc040, 0x40a0,
];
const SMALL_F32: [f32; 8] = [0.0, 1.0, -1.0, 2.0, -2.0, 3.0, -3.0, 5.0];

/// f16 bit patterns of `0.0625, -0.25, 0.5, 0.75`.
const F16_QUAD: [u16; 4] = [0x2c00, 0xb400, 0x3800, 0x3a00];

/// f16 bit patterns of an ascending 8-entry Lloyd-Max codebook:
/// `-1, -0.5, -0.25, -0.125, 0.125, 0.25, 0.5, 1`.
const LLOYD3_CB: [u16; 8] = [
    0xbc00, 0xb800, 0xb400, 0xb000, 0x3000, 0x3400, 0x3800, 0x3c00,
];

fn f32x2(a: f32, b: f32) -> [u8; 8] {
    let mut out = [0u8; 8];
    out[..4].copy_from_slice(&a.to_le_bytes());
    out[4..].copy_from_slice(&b.to_le_bytes());
    out
}

fn f16x4(bits: [u16; 4]) -> [u8; 8] {
    let mut out = [0u8; 8];
    for (i, b) in bits.iter().enumerate() {
        out[2 * i..2 * i + 2].copy_from_slice(&b.to_le_bytes());
    }
    out
}

/// One group of weights for `q`. `salt` shifts the payload (and the element
/// values of the unquantized formats) so distinct rows/groups of a synthetic
/// tensor are distinct byte-wise.
pub fn group_bytes(q: CpuQuant, salt: usize) -> Vec<u8> {
    let mut bytes: Vec<u8> = (0..q.group_bytes())
        .map(|i| (((i + salt) * 37 + 11) & 0xFF) as u8)
        .collect();
    match q {
        CpuQuant::Mq4G256 | CpuQuant::Hfq4G256 => bytes[..8].copy_from_slice(&f32x2(0.03125, -0.5)),
        CpuQuant::Mq6G256 | CpuQuant::Hfq6G256 => {
            bytes[..8].copy_from_slice(&f32x2(0.0078125, -0.125))
        }
        CpuQuant::Mq3G256 => bytes[..8].copy_from_slice(&f32x2(0.015625, 0.25)),
        CpuQuant::Mq3G256Lloyd => {
            let mut cb = [0u8; 16];
            for (k, b) in LLOYD3_CB.iter().enumerate() {
                cb[2 * k..2 * k + 2].copy_from_slice(&b.to_le_bytes());
            }
            bytes[..16].copy_from_slice(&cb);
        }
        CpuQuant::Mq4G256V2
        | CpuQuant::Mq3G256V2
        | CpuQuant::Mq5G256V2
        | CpuQuant::Mq6G256V2
        | CpuQuant::Mq2G256V2 => bytes[..8].copy_from_slice(&f16x4(F16_QUAD)),
        CpuQuant::Mq4CG256 => {
            // fp16 [scale][zero] + 4 B padding.
            bytes[..4].copy_from_slice(&f16x4(F16_QUAD)[..4]);
        }
        CpuQuant::Hfq3G256
        | CpuQuant::Hfq2G256
        | CpuQuant::Hfq4G128
        | CpuQuant::Hfq3G128
        | CpuQuant::Hfq2G128
        | CpuQuant::Mq2G256
        | CpuQuant::Mq5G256 => bytes[..8].copy_from_slice(&f32x2(0.03125, -0.5)),
        CpuQuant::Tq2G128 | CpuQuant::Bq1G128 => {
            // fp16 `d`, then the packed codes.
            bytes[..2].copy_from_slice(&0x3800u16.to_le_bytes());
        }
        CpuQuant::Mq2G256Lloyd | CpuQuant::Mq2G256LloydU => {
            // 4-entry fp16 codebook: -1, -0.25, 0.25, 1.
            bytes[..8].copy_from_slice(&f16x4([0xbc00, 0xb400, 0x3400, 0x3c00]));
        }
        CpuQuant::Mq4G256Lloyd => {
            // 16-entry fp16 codebook: -1 .. 1 in 0.125 steps is overkill; use
            // eight values duplicated so the index still varies.
            let cb = [
                0xbc00u16, 0xb800, 0xb400, 0xb000, 0x3000, 0x3400, 0x3800, 0x3c00, 0xbc00, 0xb800,
                0xb400, 0xb000, 0x3000, 0x3400, 0x3800, 0x3c00,
            ];
            let mut hdr = [0u8; 32];
            for (k, b) in cb.iter().enumerate() {
                hdr[2 * k..2 * k + 2].copy_from_slice(&b.to_le_bytes());
            }
            bytes[..32].copy_from_slice(&hdr);
        }
        CpuQuant::Q8F16 => bytes[..2].copy_from_slice(&0x3800u16.to_le_bytes()),
        CpuQuant::F16 => {
            for (j, b) in bytes.chunks_mut(2).enumerate() {
                b.copy_from_slice(&SMALL_F16[(j + salt) % 8].to_le_bytes());
            }
        }
        CpuQuant::Bf16 => {
            for (j, b) in bytes.chunks_mut(2).enumerate() {
                b.copy_from_slice(&SMALL_BF16[(j + salt) % 8].to_le_bytes());
            }
        }
        CpuQuant::F32 => {
            for (j, b) in bytes.chunks_mut(4).enumerate() {
                b.copy_from_slice(&SMALL_F32[(j + salt) % 8].to_le_bytes());
            }
        }
    }
    bytes
}

/// A `[m, k]` weight tensor's bytes, group by group.
pub fn weight_bytes(q: CpuQuant, m: usize, k: usize) -> Vec<u8> {
    let groups = k / q.group_elems();
    let mut out = Vec::with_capacity(m * (k / q.group_elems()) * q.group_bytes());
    for row in 0..m {
        for g in 0..groups {
            out.extend_from_slice(&group_bytes(q, row * groups + g));
        }
    }
    out
}
