#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 Kaden Schutt
# hipfire — see LICENSE and NOTICE in the project root.
"""Lifecycle check: deprecated surfaces stay opt-in, and every knob has a status.

(a) No default config path reaches deprecated code:
    - every config field marked `// lifecycle: deprecated since …` is either a
      gate whose schema default is inert (off / empty / false) or a tuning knob
      that only matters once a gate is on;
    - the default KV names (`memory.kv_cache`, `memory.kv_k`) and the Qwen/llama
      `auto` resolution never select a deprecated KV name or Givens asym mode;
    - registry cards and the copyable `docs/configs/*.toml` profiles never set
      a deprecated key or value;
    - CI entry points (`scripts/no-gpu-ci.sh`, `.github/workflows/*`,
      `.githooks/*`) never invoke a deprecated script;
    - deprecated code that IS reached by default (only the extension-based
      MQ4R / DS4 MQ2R route selection) is listed in DEFAULT_REACHED_ALLOWLIST.
(b) Every env var and config key carries a lifecycle status:
    - `docs/CONFIG.md` lifecycle table == schema keys + derived status;
    - `docs/env-vars.md` generated inventory == `HIPFIRE_*` token scan + status.

`--write` regenerates both generated tables. Exit 0 = pass, 1 = drift/violation.
"""

from __future__ import annotations

import json
import re
import subprocess
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MARK = "lifecycle: deprecated since 0.4.0, removal 0.5.0"
CONFIG_RS = ROOT / "crates/hipfire-config/src/lib.rs"
KV_MODE_RS = ROOT / "crates/hipfire-runtime/src/kv_mode.rs"
CONFIG_MD = ROOT / "docs/CONFIG.md"
ENV_MD = ROOT / "docs/env-vars.md"
CFG_BEGIN = "<!-- lifecycle-table:begin (generated by scripts/check-lifecycle.py --write) -->"
CFG_END = "<!-- lifecycle-table:end -->"
ENV_BEGIN = "<!-- env-inventory:begin (generated by scripts/check-lifecycle.py --write) -->"
ENV_END = "<!-- env-inventory:end -->"

# Deprecated config fields that switch a deprecated feature on, with the inert
# schema default each must keep. Every other deprecated field must be a tuning
# knob in DEPRECATED_TUNING (read only once one of these gates is on).
DEPRECATED_GATES = {
    "memory.cask.sidecar": 'DefaultValue::String("")',
    "memory.cask.enabled": "DefaultValue::Bool(false)",
    "memory.cask.auto_attach": "DefaultValue::Bool(false)",
    "speculation.prefill.mode": 'DefaultValue::String("off")',
    "speculation.prefill.drafter": 'DefaultValue::String("")',
}
DEPRECATED_TUNING = {
    "memory.cask.budget",
    "memory.cask.beta",
    "memory.cask.handoff_tokens",
    "memory.cask.core_fraction",
    "memory.cask.fold",
    "speculation.prefill.threshold",
    "speculation.prefill.keep_ratio",
    "speculation.prefill.alpha",
    "speculation.prefill.min_keep",
    "speculation.prefill.sink",
    "speculation.prefill.recent",
    "speculation.prefill.block",
    "speculation.prefill.drafter_device",
    "speculation.prefill.profile",
    "speculation.prefill.sparse_threshold",
    "speculation.prefill.drafter_kv",
    "diagnostic.pflash.score_layer",
}
# Deprecated env knobs that are not schema aliases (developer namespace or
# unread harness exports). Their unset default is the supported behaviour.
DEPRECATED_ENV = {
    "HIPFIRE_DFLASH_CTX_CAP": "legacy contiguous DFlash cap",
    "HIPFIRE_CASK_OFF": "unread CASK harness export",
}
# Any variable named for a deprecated feature is deprecated with it.
DEPRECATED_ENV_NAME = re.compile(r"PFLASH|CASK|TRIATT")
# Env vars that stay supported but have deprecated VALUES.
ENV_VALUE_NOTES = {
    "HIPFIRE_DFLASH_WINDOW": "`0` (legacy contiguous DFlash) deprecated, removal 0.5.0",
    "HIPFIRE_KV_MODE": "`asymN`/`turbo*` values deprecated, removal 0.5.0",
}
# Developer-namespace spellings of deprecated env knobs (for TOML profiles).
DEPRECATED_DEVELOPER_KEYS = {"dflash_ctx_cap", "cask_off"}
# Deprecated code that the default path still reaches, by explicit decision:
# it is the only way to select the route today, so it warns nowhere.
DEFAULT_REACHED_ALLOWLIST = {
    ("crates/hipfire-runtime/src/config.rs", "MQ4R route selection by file extension"),
    ("crates/hipfire-runtime/src/config.rs", "DS4 MQ2R selection by file extension"),
    ("crates/hipfire-cli/src/serve/mod.rs", "MQ4R route selection by file extension"),
    ("crates/hipfire-arch-deepseek4/src/deepseek4.rs", "DS4 MQ2R selection by file extension"),
}
CI_ENTRY_GLOBS = ["scripts/no-gpu-ci.sh", ".github/workflows/*", ".githooks/*"]
KV_CONFIG_KEYS = {"kv_cache", "kv_mode", "kv_k", "default_kv_mode", "memory.kv_cache", "memory.kv_k"}
STATUSES = ("stable", "experimental", "developer", "harness", "deprecated")


def git_files(*patterns: str) -> list[str]:
    out = subprocess.run(
        ["git", "ls-files", "--", *patterns], cwd=ROOT, check=True, capture_output=True, text=True
    ).stdout
    return [line for line in out.splitlines() if line and (ROOT / line).is_file()]


# ── Rust schema parsing ──────────────────────────────────────────────────────


def split_args(text: str) -> list[str]:
    """Split a macro argument list on top-level commas (strings/brackets aware)."""
    args, depth, cur, i = [], 0, [], 0
    while i < len(text):
        c = text[i]
        if c == '"':
            j = i + 1
            while text[j] != '"':
                j += 2 if text[j] == "\\" else 1
            cur.append(text[i : j + 1])
            i = j + 1
            continue
        if c in "([{":
            depth += 1
        elif c in ")]}":
            depth -= 1
        if c == "," and depth == 0:
            args.append("".join(cur).strip())
            cur = []
        else:
            cur.append(c)
        i += 1
    tail = "".join(cur).strip()
    if tail:
        args.append(tail)
    return args


def balanced(text: str, start: int) -> int:
    """Index just past the bracket that closes text[start]."""
    depth, i = 0, start
    while True:
        c = text[i]
        if c == '"':
            i += 1
            while text[i] != '"':
                i += 2 if text[i] == "\\" else 1
        elif c in "([{":
            depth += 1
        elif c in ")]}":
            depth -= 1
            if depth == 0:
                return i + 1
        i += 1


def lit(arg: str) -> str | None:
    m = re.fullmatch(r'(?:Some\()?"((?:[^"\\]|\\.)*)"\)?', arg.strip())
    return m.group(1) if m else None


# Positional (default, experimental, env) indices per schema macro.
MACROS = {
    "field": (4, 7, 8),
    "bridge_field": (4, 6, 7),
    "process_bool_field": (3, 4, 5),
    "process_auto_bool_field": (None, 3, 4),
    "process_field": (3, 5, 6),
    "diagnostic_bool_field": (2, None, 3),
    "diagnostic_field": (2, None, 4),
}


def schema_fields() -> list[dict]:
    text = CONFIG_RS.read_text(encoding="utf-8")
    start = text.index("pub static FIELDS: &[ConfigField] = &[")
    open_at = text.index("[", text.index("= &[", start) + 3)
    end = balanced(text, open_at)
    body = text[open_at + 1 : end - 1]
    fields, pos = [], 0
    entry = re.compile(r"(?m)^    (?:([a-z_]+)!\(|ConfigField \{)")
    while True:
        m = entry.search(body, pos)
        if not m:
            break
        close = balanced(body, m.end() - 1)
        inner = body[m.end() : close - 1]
        # Comment lines directly above this entry.
        comments, k = [], m.start()
        lines_above = body[:k].rstrip("\n").split("\n")
        for line in reversed(lines_above):
            if line.strip().startswith("//"):
                comments.append(line)
            else:
                break
        deprecated = any(MARK in line for line in comments)
        if m.group(1):
            name = m.group(1)
            if name not in MACROS:
                raise SystemExit(f"check-lifecycle: unknown schema macro {name}! in FIELDS")
            args = split_args(inner)
            d_i, e_i, env_i = MACROS[name]
            key, legacy = lit(args[0]), lit(args[1])
            default = args[d_i] if d_i is not None else 'DefaultValue::String("auto")'
            if name == "process_bool_field":
                default = f"DefaultValue::Bool({args[d_i]})"
            if name == "diagnostic_bool_field":
                default = f"DefaultValue::Bool({args[d_i]})"
            experimental = True if e_i is None else args[e_i].strip() == "true"
            env = lit(args[env_i]) if args[env_i].strip() != "None" else None
        else:
            kv = dict(
                (a.split(":", 1)[0].strip(), a.split(":", 1)[1].strip())
                for a in split_args(inner)
                if ":" in a
            )
            key, legacy = lit(kv["key"]), lit(kv["legacy_key"])
            default = kv["default"]
            experimental = kv["experimental"] == "true"
            env = lit(kv["env_compat"]) if kv["env_compat"] != "None" else None
        fields.append(
            dict(key=key, legacy=legacy, default=default, experimental=experimental, env=env, deprecated=deprecated)
        )
        pos = close
    return fields


def config_status(field: dict) -> str:
    if field["deprecated"]:
        return "deprecated"
    return "experimental" if field["experimental"] else "stable"


def bootstrap_env() -> set[str]:
    text = CONFIG_RS.read_text(encoding="utf-8")
    m = re.search(r"const BOOTSTRAP_ENV: &\[&str\] = &\[(.*?)\];", text, re.S)
    return set(re.findall(r'"([A-Z0-9_]+)"', m.group(1)))


def deprecated_kv_names() -> set[str]:
    text = KV_MODE_RS.read_text(encoding="utf-8")
    m = re.search(r"pub const DEPRECATED_KV_NAMES: &\[&str\] = &\[(.*?)\];", text, re.S)
    if not m:
        raise SystemExit("check-lifecycle: DEPRECATED_KV_NAMES not found in kv_mode.rs")
    return set(re.findall(r'"([^"]+)"', m.group(1)))


def fn_body(text: str, name: str) -> str:
    start = text.index(f"fn {name}(")
    brace = text.index("{", text.index(")", start))
    return text[brace : balanced(text, brace)]


# ── (a) default paths ────────────────────────────────────────────────────────


def check_defaults(fields: list[dict], kv_bad: set[str]) -> list[str]:
    errors: list[str] = []
    by_key = {f["key"]: f for f in fields}
    deprecated = {f["key"] for f in fields if f["deprecated"]}
    for key, inert in DEPRECATED_GATES.items():
        field = by_key.get(key)
        if field is None or not field["deprecated"]:
            errors.append(f"(a) gate {key} missing or not marked `// {MARK} — …`")
        elif field["default"].replace(" ", "") != inert.replace(" ", ""):
            errors.append(f"(a) gate {key} default {field['default']} is not inert ({inert})")
    unclassified = deprecated - set(DEPRECATED_GATES) - DEPRECATED_TUNING
    for key in sorted(unclassified):
        errors.append(f"(a) deprecated field {key} is neither a gate nor a tuning knob in check-lifecycle.py")
    for key in sorted(DEPRECATED_TUNING - deprecated):
        errors.append(f"(a) tuning knob {key} is not marked deprecated in the schema")
    for key in ("memory.kv_cache", "memory.kv_k"):
        default = by_key[key]["default"]
        value = re.search(r'"([^"]*)"', default)
        if value and value.group(1) in kv_bad:
            errors.append(f"(a) {key} default {value.group(1)!r} is a deprecated KV name")
    kv_text = KV_MODE_RS.read_text(encoding="utf-8")
    if re.search(r"\bAsym[234]\b", fn_body(kv_text, "qwen_auto_default_pair")):
        errors.append("(a) kv_mode::qwen_auto_default_pair can select Givens asym")
    for arm in re.findall(r'^\s*(.*"auto".*=>.*)$', fn_body(kv_text, "normalize_full"), re.M):
        if re.search(r"\bAsym[234]\b", arm):
            errors.append(f"(a) llama `auto` resolves to Givens asym: {arm.strip()}")

    legacy_to_key = {f["legacy"]: f["key"] for f in fields}
    deprecated_names = deprecated | {k for k, v in legacy_to_key.items() if v in deprecated}

    def scan(obj, where: str, path: str = "") -> None:
        if isinstance(obj, dict):
            for k, v in obj.items():
                full = f"{path}.{k}" if path else k
                if k in deprecated_names or full in deprecated_names:
                    errors.append(f"(a) {where}: sets deprecated key {full}")
                if (k in KV_CONFIG_KEYS or full in KV_CONFIG_KEYS) and isinstance(v, str) and v in kv_bad:
                    errors.append(f"(a) {where}: {full} = {v!r} is a deprecated KV name")
                if path == "developer" and k in DEPRECATED_DEVELOPER_KEYS:
                    errors.append(f"(a) {where}: sets deprecated developer.{k}")
                if path == "developer" and k == "dflash_window" and str(v) == "0":
                    errors.append(f"(a) {where}: developer.dflash_window = 0 (legacy contiguous DFlash)")
                scan(v, where, full)
        elif isinstance(obj, list):
            for v in obj:
                scan(v, where, path)

    for name in git_files("registry/*.json"):
        data = json.loads((ROOT / name).read_text(encoding="utf-8"))
        # Registry cards: only recommended settings / KV defaults are config.
        def cards(o):
            if isinstance(o, dict):
                for k, v in o.items():
                    if k in ("recommended_settings", "settings"):
                        scan(v, name)
                    elif k == "default_kv_mode" and isinstance(v, str) and v in kv_bad:
                        errors.append(f"(a) {name}: default_kv_mode {v!r} is a deprecated KV name")
                    else:
                        cards(v)
            elif isinstance(o, list):
                for v in o:
                    cards(v)

        cards(data)
    for name in git_files("docs/configs/*.toml"):
        scan(tomllib.loads((ROOT / name).read_text(encoding="utf-8")), name)

    deprecated_scripts = [
        Path(p).name
        for p in git_files("scripts/*.sh", "scripts/*.py")
        if MARK in "\n".join((ROOT / p).read_text(encoding="utf-8", errors="ignore").splitlines()[:12])
    ]
    for entry in git_files(*CI_ENTRY_GLOBS):
        text = (ROOT / entry).read_text(encoding="utf-8", errors="ignore")
        for script in deprecated_scripts:
            if re.search(rf"(?<![\w-]){re.escape(script)}\b", text):
                errors.append(f"(a) CI entry {entry} invokes deprecated {script}")

    # Markers that say the default path reaches them must be allowlisted.
    for path in git_files("crates/*.rs", "crates/**/*.rs"):
        for line in (ROOT / path).read_text(encoding="utf-8", errors="ignore").splitlines():
            if MARK in line and "no runtime warning" in line:
                if not any(path == p and r in line for p, r in DEFAULT_REACHED_ALLOWLIST):
                    errors.append(f"(a) {path}: default-reached deprecated marker not allowlisted: {line.strip()}")
    return errors


# ── (b) generated docs ───────────────────────────────────────────────────────


def config_table(fields: list[dict]) -> str:
    rows = [
        CFG_BEGIN,
        "",
        f"**Count:** {len(fields)} schema keys, plus the `developer.<name>` namespace.",
        "",
        "| Key | Legacy key | Env | Lifecycle |",
        "|---|---|---|---|",
    ]
    for f in sorted(fields, key=lambda f: f["key"]):
        env = f"`{f['env']}`" if f["env"] else ""
        rows.append(f"| `{f['key']}` | `{f['legacy']}` | {env} | {config_status(f)} |")
    rows.append("| `developer.<name>` | | `HIPFIRE_<NAME>` | developer |")
    rows += ["", CFG_END]
    return "\n".join(rows)


TOKEN = re.compile(r"\bHIPFIRE_[A-Z0-9_]*[A-Z0-9]\b")


def env_scan() -> dict[str, list[str]]:
    # HIPFIRE_* tokens, plus non-HIPFIRE bootstrap names (e.g. HF_ENDPOINT).
    extra = sorted(n for n in bootstrap_env() if not n.startswith("HIPFIRE_"))
    extra_re = re.compile(r"\b(?:" + "|".join(map(re.escape, extra)) + r")\b") if extra else None
    seen: dict[str, list[str]] = {}
    for path in sorted(git_files("*.rs", "*.py", "*.sh")):
        if path == "scripts/check-lifecycle.py":  # names deprecated vars itself
            continue
        text = (ROOT / path).read_text(encoding="utf-8", errors="ignore")
        names = set(TOKEN.findall(text))
        if extra_re:
            names |= set(extra_re.findall(text))
        for name in names:
            seen.setdefault(name, []).append(path)
    return seen


def deprecated_paths() -> set[str]:
    out = set()
    for path in git_files("*.rs", "*.py", "*.sh"):
        head = (ROOT / path).read_text(encoding="utf-8", errors="ignore").splitlines()[:12]
        if any(MARK in line for line in head):
            out.add(path)
            if path.endswith("/src/lib.rs"):
                out.add(path[: -len("src/lib.rs")])
    return out


def is_product(path: str) -> bool:
    parts = path.split("/")
    return parts[0] == "crates" and "src" in parts and "tests" not in parts and "examples" not in parts


def env_status(name: str, paths: list[str], alias: dict[str, dict], boot: set[str], dep: set[str]) -> str:
    field = alias.get(name)
    if name in DEPRECATED_ENV or DEPRECATED_ENV_NAME.search(name) or (field and field["deprecated"]):
        status = "deprecated"
    elif paths and all(p in dep or any(p.startswith(d) for d in dep if d.endswith("/")) for p in paths):
        status = "deprecated"
    elif field:
        status = config_status(field)
    elif name in boot:
        status = "stable"
    elif any(is_product(p) for p in paths):
        status = "developer"
    else:
        status = "harness"
    note = ENV_VALUE_NOTES.get(name)
    return f"{status}; {note}" if note else status


def env_table(fields: list[dict]) -> tuple[str, dict[str, str]]:
    alias = {f["env"]: f for f in fields if f["env"]}
    boot, dep = bootstrap_env(), deprecated_paths()
    scan = env_scan()
    statuses = {n: env_status(n, p, alias, boot, dep) for n, p in scan.items()}
    rows = [
        ENV_BEGIN,
        "",
        "**Generation method:** token scan over tracked `*.rs`, `*.py`, and `*.sh` (`scripts/check-lifecycle.py --write`).",
        "**Columns:** variable; up to two lexical source paths; lifecycle status (see [Lifecycle status](#lifecycle-status)).",
        f"**Count:** {len(scan)}",
        "",
        "| Variable | Example source path(s) | Lifecycle |",
        "|---|---|---|",
    ]
    for name in sorted(scan):
        rows.append(f"| `{name}` | {', '.join(scan[name][:2])} | {statuses[name]} |")
    rows += ["", ENV_END]
    return "\n".join(rows), statuses


def block(text: str, begin: str, end: str, doc: Path) -> tuple[int, int]:
    b = text.find(begin)
    e = text.find(end)
    if b < 0 or e < 0:
        raise SystemExit(f"check-lifecycle: {doc.relative_to(ROOT)} lacks the {begin!r} … {end!r} block")
    return b, e + len(end)


def doc_rows(text: str, cols: int) -> dict[str, str]:
    rows = {}
    for line in text.splitlines():
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        if len(cells) == cols and cells[0].startswith("`"):
            rows[cells[0].strip("`")] = cells[-1]
    return rows


def main() -> int:
    write = "--write" in sys.argv[1:]
    fields = schema_fields()
    kv_bad = deprecated_kv_names()
    errors = check_defaults(fields, kv_bad)

    cfg_text = CONFIG_MD.read_text(encoding="utf-8")
    env_text = ENV_MD.read_text(encoding="utf-8")
    cfg_new = config_table(fields)
    env_new, env_statuses = env_table(fields)
    cb, ce = block(cfg_text, CFG_BEGIN, CFG_END, CONFIG_MD)
    eb, ee = block(env_text, ENV_BEGIN, ENV_END, ENV_MD)
    if write:
        CONFIG_MD.write_text(cfg_text[:cb] + cfg_new + cfg_text[ce:], encoding="utf-8")
        ENV_MD.write_text(env_text[:eb] + env_new + env_text[ee:], encoding="utf-8")
        print("check-lifecycle: regenerated docs/CONFIG.md lifecycle table and docs/env-vars.md inventory")
    else:
        want_cfg = {f["key"]: config_status(f) for f in fields}
        want_cfg["developer.<name>"] = "developer"
        have_cfg = doc_rows(cfg_text[cb:ce], 4)
        for key in sorted(set(want_cfg) | set(have_cfg)):
            if have_cfg.get(key) != want_cfg.get(key):
                errors.append(
                    f"(b) docs/CONFIG.md lifecycle: {key}: doc={have_cfg.get(key)!r} schema={want_cfg.get(key)!r}"
                )
        have_env = doc_rows(env_text[eb:ee], 3)
        for name in sorted(set(env_statuses) | set(have_env)):
            if have_env.get(name) != env_statuses.get(name):
                errors.append(
                    f"(b) docs/env-vars.md inventory: {name}: doc={have_env.get(name)!r} derived={env_statuses.get(name)!r}"
                )
    for name, status in env_statuses.items():
        if status.split(";")[0] not in STATUSES:
            errors.append(f"(b) {name}: unknown lifecycle status {status!r}")

    if errors:
        print("check-lifecycle: FAIL")
        for error in errors[:200]:
            print(f"  {error}")
        if len(errors) > 200:
            print(f"  … {len(errors) - 200} more")
        print("Regenerate generated tables with: python3 scripts/check-lifecycle.py --write")
        return 1
    deprecated = sum(1 for f in fields if f["deprecated"])
    dep_env = sum(1 for s in env_statuses.values() if s.startswith("deprecated"))
    print(
        f"check-lifecycle: {len(fields)} config keys ({deprecated} deprecated, gates inert), "
        f"{len(env_statuses)} env vars ({dep_env} deprecated) carry a lifecycle status; "
        f"{len(DEFAULT_REACHED_ALLOWLIST)} allowlisted default-reached deprecated route(s)"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
