#include <hip/hip_runtime.h>
#include <algorithm>
#include <cmath>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <random>
#include <vector>
#include "../../../kernels/src/gdn_chunk_scan_prep.gfx1201.hip"
#include "../../../kernels/src/gdn_chunk_scan_kkt_solve.gfx1201.hip"
extern "C" __global__ void gdn_chunk_scan(const unsigned short*,const unsigned short*,const unsigned short*,const unsigned short*,const float*,const float*,signed char*,float*,_Float16*,float*,int,int);
extern "C" __global__ void gdn_chunk_scan_f32_edge(const unsigned short*,const unsigned short*,const unsigned short*,const unsigned short*,const float*,const float*,const float*,float*,float*,int,int);
#define HIP_OK(x) do{hipError_t z=(x);if(z!=hipSuccess){std::fprintf(stderr,"HIP:%s\n",hipGetErrorString(z));std::exit(2);}}while(0)
static constexpr int T=1024,S=512,HD=128,HK=16,HV=48,XD=10240,C=64;
static float bf(uint16_t x){_Float16 h;std::memcpy(&h,&x,2);return float(h);}
static uint64_t hash64(const void*p,size_t n){const uint8_t*b=(const uint8_t*)p;uint64_t h=1469598103934665603ull;for(size_t i=0;i<n;++i){h^=b[i];h*=1099511628211ull;}return h;}
static void metric(const char*n,const std::vector<float>&got,const std::vector<double>&ref){long double e=0,r=0;double ma=0;size_t nf=0,first=got.size();for(size_t i=0;i<got.size();++i){double d=double(got[i])-ref[i];e+=d*d;r+=ref[i]*ref[i];ma=std::max(ma,std::abs(d));nf+=!std::isfinite(got[i]);if(first==got.size()&&d!=0)first=i;}double nr=std::sqrt((double)(e/got.size()))/std::sqrt((double)(r/got.size()));std::printf("%s_nrmse=%.9g %s_max_abs=%.9g %s_nonfinite=%zu %s_first=%zu\n",n,nr,n,ma,n,nf,n,first);}
int main(){
 std::mt19937 rng(20260919);std::uniform_real_distribution<float>dx(-.25,.25),dw(-.08,.08),da(-2,2),db(-3,3),de(-2e-5f,2e-5f);
 std::vector<float>x(size_t(T)*XD),w(size_t(XD)*4),cs(size_t(XD)*3),G(size_t(T)*HV),beta(size_t(T)*HV),dt(HV),al(HV);for(auto&z:x)z=dx(rng);for(auto&z:w)z=dw(rng);for(auto&z:cs)z=dx(rng);for(auto&z:G)z=da(rng);for(auto&z:beta)z=db(rng);for(auto&z:dt)z=.25f*dx(rng);for(auto&z:al)z=-3+dx(rng);
 std::vector<uint16_t>q(size_t(T)*HK*HD),k(q.size()),v(size_t(T)*HV*HD),A(size_t(S)*HV*C);
 std::vector<signed char>sq(size_t(HV)*HD*HD),sq0(sq.size());std::vector<float>sc(size_t(HV)*HD),sc0(sc.size());std::vector<_Float16>ef(sq.size()),ef0(ef.size());std::vector<float>out(size_t(T)*HV*HD),edge_entry(size_t(HV)*HD*HD),edge_out(out.size()),edge_ht(edge_entry.size());
 for(int h=0;h<HV;++h)for(int vv=0;vv<HD;++vv){float mx=0,vals[HD];for(int d=0;d<HD;++d){float z=.04f*dx(rng);vals[d]=z;mx=std::max(mx,std::abs(z));}float scale=mx/127;sc0[h*HD+vv]=scale;for(int d=0;d<HD;++d){size_t o=(size_t(h)*HD+vv)*HD+d;float z=std::rint(vals[d]/scale);sq0[o]=(signed char)z;ef0[o]=(_Float16)de(rng);}}sq=sq0;sc=sc0;ef=ef0;
 float *xd,*wd,*csd,*gd,*bd,*dtd,*ald,*scd,*outd,*edge_entry_d,*edge_out_d,*edge_ht_d;uint16_t *qd,*kd,*vd,*Ad;signed char*sqd;_Float16*efd;
 HIP_OK(hipMalloc(&xd,x.size()*4));HIP_OK(hipMalloc(&wd,w.size()*4));HIP_OK(hipMalloc(&csd,cs.size()*4));HIP_OK(hipMalloc(&gd,G.size()*4));HIP_OK(hipMalloc(&bd,beta.size()*4));HIP_OK(hipMalloc(&dtd,dt.size()*4));HIP_OK(hipMalloc(&ald,al.size()*4));HIP_OK(hipMalloc(&qd,q.size()*2));HIP_OK(hipMalloc(&kd,k.size()*2));HIP_OK(hipMalloc(&vd,v.size()*2));HIP_OK(hipMalloc(&Ad,A.size()*2));HIP_OK(hipMalloc(&sqd,sq.size()));HIP_OK(hipMalloc(&scd,sc.size()*4));HIP_OK(hipMalloc(&efd,ef.size()*2));HIP_OK(hipMalloc(&outd,out.size()*4));HIP_OK(hipMalloc(&edge_entry_d,edge_entry.size()*4));HIP_OK(hipMalloc(&edge_out_d,edge_out.size()*4));HIP_OK(hipMalloc(&edge_ht_d,edge_ht.size()*4));
 HIP_OK(hipMemcpy(xd,x.data(),x.size()*4,hipMemcpyHostToDevice));HIP_OK(hipMemcpy(wd,w.data(),w.size()*4,hipMemcpyHostToDevice));HIP_OK(hipMemcpy(csd,cs.data(),cs.size()*4,hipMemcpyHostToDevice));HIP_OK(hipMemcpy(gd,G.data(),G.size()*4,hipMemcpyHostToDevice));HIP_OK(hipMemcpy(bd,beta.data(),beta.size()*4,hipMemcpyHostToDevice));HIP_OK(hipMemcpy(dtd,dt.data(),dt.size()*4,hipMemcpyHostToDevice));HIP_OK(hipMemcpy(ald,al.data(),al.size()*4,hipMemcpyHostToDevice));HIP_OK(hipMemcpy(sqd,sq.data(),sq.size(),hipMemcpyHostToDevice));HIP_OK(hipMemcpy(scd,sc.data(),sc.size()*4,hipMemcpyHostToDevice));HIP_OK(hipMemcpy(efd,ef.data(),ef.size()*2,hipMemcpyHostToDevice));
 hipLaunchKernelGGL(gdn_chunk_prep,dim3((T+63)/64,10),dim3(256),0,0,xd,wd,csd,gd,bd,dtd,ald,qd,kd,vd,T,.08838834764831845f,1e-6f);HIP_OK(hipGetLastError());HIP_OK(hipDeviceSynchronize());HIP_OK(hipMemcpy(q.data(),qd,q.size()*2,hipMemcpyDeviceToHost));HIP_OK(hipMemcpy(k.data(),kd,k.size()*2,hipMemcpyDeviceToHost));HIP_OK(hipMemcpy(v.data(),vd,v.size()*2,hipMemcpyDeviceToHost));HIP_OK(hipMemcpy(G.data(),gd,G.size()*4,hipMemcpyDeviceToHost));HIP_OK(hipMemcpy(beta.data(),bd,beta.size()*4,hipMemcpyDeviceToHost));
 std::vector<double>state(HD*HD),refout(size_t(T)*HD);std::vector<_Float16>cpu_ef(HD*HD);std::vector<signed char>cpu_sq(HD*HD);std::vector<float>cpu_sc(HD);
 for(int vv=0;vv<HD;++vv){cpu_sc[vv]=sc0[vv];for(int d=0;d<HD;++d){size_t o=size_t(vv)*HD+d;state[o]=double(sq0[o])*sc0[vv];cpu_ef[o]=ef0[o];cpu_sq[o]=sq0[o];}}
 for(int seg=0;seg<2;++seg){int row0=seg*S;if(seg==1){for(int vv=0;vv<HD;++vv)for(int d=0;d<HD;++d)edge_entry[(size_t(vv)*HD+d)]=float(sq[size_t(vv)*HD+d])*sc[vv];HIP_OK(hipMemcpy(edge_entry_d,edge_entry.data(),edge_entry.size()*4,hipMemcpyHostToDevice));}hipLaunchKernelGGL(gdn_chunk_kkt_solve,dim3(8,16),dim3(128),0,0,kd,gd,bd,Ad,row0,S);HIP_OK(hipGetLastError());hipLaunchKernelGGL(gdn_chunk_scan,dim3(2,48),dim3(256),0,0,qd,kd,vd,Ad,gd,bd,sqd,scd,efd,outd,row0,S);HIP_OK(hipGetLastError());HIP_OK(hipDeviceSynchronize());HIP_OK(hipMemcpy(sq.data(),sqd,sq.size(),hipMemcpyDeviceToHost));HIP_OK(hipMemcpy(sc.data(),scd,sc.size()*4,hipMemcpyDeviceToHost));HIP_OK(hipMemcpy(ef.data(),efd,ef.size()*2,hipMemcpyDeviceToHost));HIP_OK(hipMemcpy(out.data(),outd,out.size()*4,hipMemcpyDeviceToHost));
  if(seg==1){hipLaunchKernelGGL(gdn_chunk_scan_f32_edge,dim3(2,48),dim3(256),0,0,qd,kd,vd,Ad,gd,bd,edge_entry_d,edge_ht_d,edge_out_d,row0,S);HIP_OK(hipGetLastError());HIP_OK(hipDeviceSynchronize());HIP_OK(hipMemcpy(edge_out.data(),edge_out_d,edge_out.size()*4,hipMemcpyDeviceToHost));size_t edge_bad=0;for(size_t i=size_t(row0)*HV*HD;i<size_t(row0+S)*HV*HD;++i)edge_bad+=std::memcmp(&out[i],&edge_out[i],4)!=0;std::printf("seg1_q8_vs_dequant_edge_output_bit_bad=%zu\n",edge_bad);}
  for(int t=row0;t<row0+S;++t){double gate=G[size_t(t)*HV]-(t%C?G[size_t(t-1)*HV]:0.0f),decay=std::exp(gate);for(int vv=0;vv<HD;++vv){double pred=0;for(int d=0;d<HD;++d)pred+=bf(k[(size_t(t)*HK)*HD+d])*state[vv*HD+d];double delta=double(beta[size_t(t)*HV])*(bf(v[(size_t(t)*HV)*HD+vv])-decay*pred);double ov=0;for(int d=0;d<HD;++d){state[vv*HD+d]=decay*state[vv*HD+d]+bf(k[(size_t(t)*HK)*HD+d])*delta;ov+=bf(q[(size_t(t)*HK)*HD+d])*state[vv*HD+d];}refout[size_t(t)*HD+vv]=ov;}}
  for(int vv=0;vv<HD;++vv){double mx=0;for(int d=0;d<HD;++d){size_t o=size_t(vv)*HD+d;state[o]+=double(cpu_ef[o]);mx=std::max(mx,std::abs(state[o]));}float scale=mx>0?float(mx/127.0):1.0f,inv=mx>0?127.0f/float(mx):0.0f;cpu_sc[vv]=scale;for(int d=0;d<HD;++d){size_t o=size_t(vv)*HD+d;float z=float(state[o]);float qf=std::min(std::max(std::rint(z*inv),-128.0f),127.0f);cpu_sq[o]=(signed char)qf;cpu_ef[o]=(_Float16)(z-qf*scale);state[o]=double(cpu_sq[o])*scale;}}
  std::vector<float>gotout(size_t(S)*HD),gotstate(HD*HD);std::vector<double>refseg(size_t(S)*HD),refstate(HD*HD);for(int t=0;t<S;++t)for(int vv=0;vv<HD;++vv){gotout[size_t(t)*HD+vv]=out[(size_t(row0+t)*HV)*HD+vv];refseg[size_t(t)*HD+vv]=refout[size_t(row0+t)*HD+vv];}for(int vv=0;vv<HD;++vv)for(int d=0;d<HD;++d){size_t o=size_t(vv)*HD+d;gotstate[o]=float(sq[o])*sc[vv];refstate[o]=state[o];}
  char no[32],ns[32];std::snprintf(no,sizeof(no),"seg%d_output",seg);std::snprintf(ns,sizeof(ns),"seg%d_state",seg);metric(no,gotout,refseg);metric(ns,gotstate,refstate);
  size_t cb=0,sb=0,eb=0,fc=HD*HD,fs=HD,fe=HD*HD;for(size_t o=0;o<HD*HD;++o){bool d=cpu_sq[o]!=sq[o];cb+=d;if(d&&fc==HD*HD)fc=o;d=std::memcmp(&cpu_ef[o],&ef[o],2)!=0;eb+=d;if(d&&fe==HD*HD)fe=o;}for(int vv=0;vv<HD;++vv){bool d=std::memcmp(&cpu_sc[vv],&sc[vv],4)!=0;sb+=d;if(d&&fs==HD)fs=vv;}
  std::printf("seg%d first8",seg);for(int i=0;i<8;++i)std::printf(" %.9g/%.9g",gotout[i],refseg[i]);std::printf(" gate0=%.9g G0=%.9g beta0=%.9g q0=%.9g k0=%.9g v0=%.9g scale0=%.9g/%.9g ef0=%.9g/%.9g\n",std::exp(G[size_t(row0)*HV]),G[size_t(row0)*HV],beta[size_t(row0)*HV],bf(q[(size_t(row0)*HK)*HD]),bf(k[(size_t(row0)*HK)*HD]),bf(v[(size_t(row0)*HV)*HD]),sc[0],cpu_sc[0],float(ef[0]),float(cpu_ef[0]));
  std::printf("seg%d code_bad=%zu first_code=%zu scale_bad=%zu first_scale=%zu ef_bad=%zu first_ef=%zu gpu_code_hash=%016llx cpu_code_hash=%016llx gpu_scale_hash=%016llx cpu_scale_hash=%016llx gpu_ef_hash=%016llx cpu_ef_hash=%016llx\n",seg,cb,fc,sb,fs,eb,fe,(unsigned long long)hash64(sq.data(),HD*HD),(unsigned long long)hash64(cpu_sq.data(),HD*HD),(unsigned long long)hash64(sc.data(),HD*4),(unsigned long long)hash64(cpu_sc.data(),HD*4),(unsigned long long)hash64(ef.data(),HD*HD*2),(unsigned long long)hash64(cpu_ef.data(),HD*HD*2));
  if(seg==0){for(int h=0;h<HV;++h)for(int vv=0;vv<HD;++vv)for(int d=0;d<HD;++d){size_t o=(size_t(h)*HD+vv)*HD+d;edge_entry[o]=float(sq[o])*sc[h*HD+vv];}HIP_OK(hipMemcpy(edge_entry_d,edge_entry.data(),edge_entry.size()*4,hipMemcpyHostToDevice));}
 }
}
